-- H2 MySQL-compatible schema for integration tests
CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `username` VARCHAR(50) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `email` VARCHAR(100),
    `nickname` VARCHAR(50),
    `avatar` VARCHAR(500),
    `bio` VARCHAR(500),
    `role` VARCHAR(20) DEFAULT 'USER',
    `status` VARCHAR(20) DEFAULT 'ACTIVE',
    `deleted` TINYINT DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_user_deleted` (`deleted`)
);

CREATE TABLE IF NOT EXISTS `post` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `content` TEXT,
    `images` TEXT,
    `emotion_score` DECIMAL(5,4),
    `emotion_label` VARCHAR(20),
    `llm_analysis` TEXT,
    `view_count` INT DEFAULT 0,
    `like_count` INT DEFAULT 0,
    `comment_count` INT DEFAULT 0,
    `status` VARCHAR(20) DEFAULT 'ANALYZING',
    `deleted` TINYINT DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_post_user_id` (`user_id`),
    INDEX `idx_post_status` (`status`),
    INDEX `idx_post_deleted` (`deleted`),
    INDEX `idx_post_emotion` (`emotion_label`),
    INDEX `idx_post_created` (`created_at`)
);

CREATE TABLE IF NOT EXISTS `comment` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `post_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    `parent_id` BIGINT,
    `content` TEXT,
    `deleted` TINYINT DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_cmt_post_id` (`post_id`),
    INDEX `idx_cmt_user_id` (`user_id`),
    INDEX `idx_cmt_parent_id` (`parent_id`),
    INDEX `idx_cmt_deleted` (`deleted`)
);

CREATE TABLE IF NOT EXISTS `interaction` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `target_id` BIGINT NOT NULL,
    `target_type` VARCHAR(20) NOT NULL,
    `type` VARCHAR(20) NOT NULL,
    `deleted` TINYINT DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE INDEX `idx_interact_uk` (`user_id`, `target_id`, `target_type`, `type`),
    INDEX `idx_interact_target` (`target_id`, `target_type`),
    INDEX `idx_interact_deleted` (`deleted`)
);

CREATE TABLE IF NOT EXISTS `user_emotion_stats` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `user_id` BIGINT NOT NULL UNIQUE,
    `positive_count` INT DEFAULT 0,
    `negative_count` INT DEFAULT 0,
    `neutral_count` INT DEFAULT 0,
    `total_posts` INT DEFAULT 0,
    `avg_emotion_score` DECIMAL(5,4) DEFAULT 0,
    `deleted` TINYINT DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_stats_user_id` (`user_id`)
);

CREATE TABLE IF NOT EXISTS `api_key_config` (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `user_id` BIGINT,
    `provider` VARCHAR(50) NOT NULL,
    `api_key` VARCHAR(500) NOT NULL,
    `is_default` TINYINT DEFAULT 0,
    `deleted` TINYINT DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_api_key_user` (`user_id`),
    INDEX `idx_api_key_provider` (`provider`)
);
